Try2AcademicPortal/AcademicPortal/AcademicPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('login/',login_view,name="login"),
    path('signup/',signup_view,name="signup"),
	path('logout/', logoutUser, name="logout"),

    path('',include('dashboard.urls')),
    
    path('cal/', include('calendarapp.urls')),

    path('todo/', include('todoapp.urls')),
    
    path('admin/', admin.site.urls),

    path('fileupload/',include('fileuploadapp.urls')),

    path('social/',include('social.urls'))
    
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Try2AcademicPortal/AcademicPortal/social/urls.py
from django.urls import path,include

from .views import *
app_name='social'
urlpatterns=[
	path('',index,name="home"),
	path('upload/',show_file,name="upload"),
	path('upload/<int:pk>/',delete_book,name="delete_book"),

]

Try2AcademicPortal/AcademicPortal/todoapp/urls.py
from django.urls import path
from . import views

app_name='todoapp'
urlpatterns = [
    path('', views.index, name="list"),
    path('update_task/<str:pk>/', views.updateTask, name="update_task"),
    path('delete/<str:pk>/', views.deleteTask, name="delete"),
]

Try2AcademicPortal/AcademicPortal/templates/todolist/delete.html
{% extends 'dashboardPage/dashboard.html' %}

{%block title%}
  Student Portal | Delete Item
  {%endblock%}

  {% block welcome %}
  {% endblock welcome %}
{% block content %}

<p>Are you sure you want to delete "{{item}}"?</p>

<a href="{% url 'todoapp:list' %}" >Cancel</a>



<form method="POST" action="">
	{% csrf_token %}
	<input type="submit" name="Confirm">
</form>

{% endblock %}

Try2AcademicPortal/AcademicPortal/templates/todolist/list.html
{% extends 'dashboardPage/dashboard.html' %}

{%block title%}
  Student Portal | ToDoList
  {%endblock%}

  {% block welcome %}
  {% endblock welcome %}
{% block content %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #b2efb761;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: var(--white);
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: var(--gray-dark);
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		color: var(--danger);
		background-color: var(--white);
        border-color: var(--danger);
	}
    
	.btn-info
	{
		color: var(--cyan);
        background-color: var(--white);
       border-color: #17a2b8;
	}

	.btn-success
	{
		
    color: var(--green);
    background-color: var(--white);
    border-color: #28a745;
	}


</style>

<div class="center-column">
	<h2>TO DO'S</h2>

	<form method="POST" action="/todo/">
		{% csrf_token %}
		{{form.title}}                      
		<input class="btn btn-success" type="submit" name="Create Task">
	</form>

	<div class="todo-list">

	{% for task in tasks %}
		<div class="item-row">
			<a class="btn btn-sm btn-info" href="{% url 'todoapp:update_task' task.id %}">Update</a>
			<a class="btn btn-sm btn-danger" href="{% url 'todoapp:delete' task.id %}">Delete</a>

			{% if task.complete == True %}
			<strike>{{task}}</strike>
			{% else %}
			<span>{{task}}</span>
			{% endif %}
		</div>
	{% endfor %}
	</div>
</div>
{% endblock %}

Try2AcademicPortal/AcademicPortal/templates/todolist/update_task.html
{% extends 'dashboardPage/dashboard.html' %}

{%block title%}
  Student Portal | Update Item
  {%endblock%}


  {% block welcome %}
  {% endblock welcome %}
{% block content %}


<h3>Update Task</h3>

<form method="POST" action="">
	{% csrf_token %}

	{{form}}
	<input type="submit" name="Update Task">


</form>

{% endblock %}