Try2AcademicPortal/AcademicPortal/AcademicPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('login/',login_view,name="login"),
    path('signup/',signup_view,name="signup"),
	path('logout/', logoutUser, name="logout"),

    path('',include('dashboard.urls')),
    
    path('cal/', include('calendarapp.urls')),

    path('todo/', include('todoapp.urls')),
    
    path('admin/', admin.site.urls),

    path('fileupload/',include('fileuploadapp.urls')),

    path('social/',include('social.urls'))
    
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Try2AcademicPortal/AcademicPortal/calendarapp/urls.py
from django.urls import path

from .views import *

app_name = 'calendarapp'
urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/', create_event, name='event_new'),
    path('event/edit/<int:pk>/', EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', EventMemberDeleteView.as_view(), name="remove_event"),
]

Try2AcademicPortal/AcademicPortal/dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('', home_view, name='home'),
    path('profile/', profile_view, name='profile'),
    path('update_profile/',update_profile_view,name='update_profile'),
    path('aboutus/',aboutus,name='aboutus'),
]

Try2AcademicPortal/AcademicPortal/fileuploadapp/urls.py
from django.urls import path,include

from . import views
app_name='fileuploadapp'
urlpatterns=[
	path('',views.index,name="home"),
	path('upload/',views.show_file,name="upload"),
	path('upload/<int:pk>/', views.delete_book,name="delete_book"),

]

Try2AcademicPortal/AcademicPortal/social/urls.py
from django.urls import path,include

from .views import *
app_name='social'
urlpatterns=[
	path('',index,name="home"),
	path('upload/',show_file,name="upload"),
	path('upload/<int:pk>/',delete_book,name="delete_book"),

]

Try2AcademicPortal/AcademicPortal/todoapp/urls.py
from django.urls import path
from . import views

app_name='todoapp'
urlpatterns = [
    path('', views.index, name="list"),
    path('update_task/<str:pk>/', views.updateTask, name="update_task"),
    path('delete/<str:pk>/', views.deleteTask, name="delete"),
]

Try2AcademicPortal/AcademicPortal/dashboard/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User 
# Create your models here.

class Student(models.Model):

    user = models.OneToOneField(User,null=True,on_delete=models.SET_NULL)
    name = models.CharField(max_length=256,null=True)
    usn = models.CharField(max_length=256,null=True)
    sex = models.CharField(max_length=256,null=True)
    email = models.EmailField(max_length=256,null=True,blank=True)
    branch = models.CharField(max_length=256,null=True,blank=True)
    sem = models.CharField(max_length=256,null=True,blank=True)
    course1 = models.CharField(max_length=256,null=True,blank=True)
    course2 = models.CharField(max_length=256,null=True,blank=True)
    course3 = models.CharField(max_length=256,null=True,blank=True)
    course4 = models.CharField(max_length=256,null=True,blank=True)
    course5 = models.CharField(max_length=256,null=True,blank=True)
    course6 = models.CharField(max_length=256,null=True,blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Personal(models.Model):

    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    avatar = models.CharField(max_length=20,null=True,blank=True,default="dist/img/avatar5.png")
    website = models.CharField(max_length=256,null=True,blank=True)
    github = models.CharField(max_length=256,null=True,blank=True)
    linked = models.CharField(max_length=256,null=True,blank=True)
    bio = models.CharField(max_length=256,null=True,blank=True)

    def __str__(self):
        return self.user.username

Try2AcademicPortal/AcademicPortal/dashboard/forms.py
from django.forms import ModelForm

        

Try2AcademicPortal/AcademicPortal/dashboard/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from dashboard.models import *

# Create your views here.
@login_required(login_url='login')
def home_view(request):
    personal = Personal.objects.get(user=request.user.id)
    avatar = personal.avatar
    content={
        'username':request.user.get_username(),
        'avatar' : avatar,
    }
    return render(request, 'dashboardPage/dashboard.html', content)

@login_required(login_url='login')
def profile_view(request):
    username =Student.objects.get(user_id=request.user.id)
    personal = Personal.objects.get(user=request.user.id)
    context={
        'student':username,
        'name':username.name,
        'usn': username.usn,
        'sex': username.sex,
        'email': username.email,
        'branch':username.branch,
        'semester':username.sem,
        'course1':username.course1,
        'course2':username.course2,
        'course3':username.course3,
        'course4':username.course4,
        'course5':username.course5,
        'course6':username.course6,
        'avatar':personal.avatar,
        'bio':personal.bio,
        'website':personal.website,
        'linked':personal.linked,
        'github':personal.github,


    }
    return render(request,'dashboardPage/profile.html',context)

@login_required(login_url='login')
def update_profile_view(request):

    if request.method == 'POST':
        username = Student.objects.get(user_id=request.user.id)
        print(username)
        name = request.POST.get('name')
        email = request.POST.get('email')
        usn = request.POST.get('usn')
        sex = request.POST.get('sex')
        branch = request.POST.get('branch')
        semester = request.POST.get('semester')
        avatar = request.POST.get('avatar')
        website = request.POST.get('website')
        linked = request.POST.get('linked')
        github = request.POST.get('github')
        bio = request.POST.get('bio')
        courseid = {}
        coursename = {}
        for i in range(1,8):
            courseid['course'+str(i)] = request.POST.get('course'+str(i))
        print(courseid)
        json_data = open('static/dist/js/branch_sem_course.json')   
        data = json.load(json_data) # deserialises it
        json_data.close()

        for info in data:
            if info['id']==branch:
                branch = info['name']
            if info['id']==semester:
                semester = info['name']
            for i in range(1,8):
                if courseid['course'+str(i)]==info['id']:
                    coursename['course'+str(i)]= info['name']

        print(branch,semester)
        print(coursename)
        print(avatar)
        username.name=name
        username.email=email
        username.usn=usn
        username.sex=sex
        username.branch=branch
        username.sem=semester
        username.course1 = coursename['course1']
        username.course2 = coursename['course2']
        username.course3 = coursename['course3']
        username.course4 = coursename['course4']
        username.course5 = coursename['course5']
        username.course6 = coursename['course6']
        if avatar == 'Female1':
            src= "dist/img/avatar2.png"
        elif avatar == 'Female2':
            src= "dist/img/avatar3.png"
        elif avatar == 'Male1':
            src= "dist/img/avatar.png"
        elif avatar == 'Male2':
            src= "dist/img/avatar4.png"
        elif avatar == 'Male3':
            src= "dist/img/avatar5.png"
        personal = Personal.objects.get(user=request.user.id)
        personal.avatar = src
        personal.website = website
        personal.github = github
        personal.linked = linked
        personal.bio = bio
        personal.save()
        username.save()
        return redirect("dashboard:profile")
    context = {}
    return render(request,'dashboardPage/studentform.html',context)


def aboutus(request):
    personal = Personal.objects.get(user=request.user.id)
    avatar = personal.avatar
    content={
        'username':request.user.get_username(),
        'avatar' : avatar,
    }
    return render(request, 'dashboardPage/aboutus2.html', content)

Try2AcademicPortal/AcademicPortal/templates/dashboardPage/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {%block title%}
    Student Portal | Dashboard
    {%endblock title%}
  </title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Bootstrap CSS for calendar app-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/profile_style.css' %}">

  {%block links%}
  {%endblock links%}
</head>

<body class="hold-transition sidebar-mini layout-fixed">

  <div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar navbar-light" style="background-color: #84919b;">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- assitor logo -->
      <a href="{% url 'dashboard:home' %}" class="brand-link">
        <img src="{% static "dist/img/Student-Portal.jpg" %}" alt="student assitor Logo"
          class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Student Portal</span>
      </a>

      <!-- Sidebar -->
      <div id="sidebar" class="sidebar">


        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="{% static request.user.personal.avatar %}" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
            <a href="{% url 'dashboard:profile'%}" class="d-block">{{request.user.username}}</a>
          </div>
        </div>

        {% url 'dashboard:home' as home %}
        {% url 'calendarapp:calendar' as calendar1 %}
        {% url 'todoapp:list' as todo %}
        {% url 'fileuploadapp:upload' as upload %}
        {% url 'dashboard:profile' as profile %}
        {% url 'dashboard:aboutus' as aboutus %}

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item menu-open">
              <a href="{% url 'dashboard:home' %}" class="nav-link {% if request.path == home %} active {% endif %}">
                <i class="nav-icon fas fa-home"></i>
                <p>
                  HOME
                </p>
              </a>

            </li>

            <li class="nav-item">
              <a href="{% url 'calendarapp:calendar' %}" class="nav-link {% if request.path == calendar1 %} active {% endif %}">
                <i class="nav-icon fas fa-calendar"></i>
                <p>
                  Calender
                </p>
              </a>

            </li>
            <li class="nav-item">
              <a href="{% url 'todoapp:list' %}" class="nav-link {% if request.path == todo %} active {% endif %}">
                <i class="nav-icon fas fa-copy"></i>
                <p>
                  To-Do List
                </p>
              </a>

            </li>
            <li class="nav-item">
              <a href="{% url 'fileuploadapp:upload'%}" class="nav-link {% if request.path == upload %} active {% endif %}">
                <i class="nav-icon fas fa-book"></i>
                <p>
                  Upload File
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'social:upload'%}" class="nav-link">
                <i class="nav-icon fa fa-cloud"></i>
                <p>
                  Social DocHub
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'dashboard:profile'%}" class="nav-link {% if request.path == profile %} active {% endif %}">
                <i class="nav-icon fa fa-cog"></i>
                <p>
                  Settings
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="/logout" class="nav-link">
                <i class="nav-icon fas fa-space-shuttle"></i>
                <p>
                  Logout
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="/aboutus" class="nav-link {% if request.path == aboutus %} active {% endif %}">
                <i class="fa fa-users nav-icon"></i>
                <p>About Us</p>
              </a>
            </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">

        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              {% block welcome %}
              <h1 class="m-0">Welcome To Student Portal</h1>
              {% endblock welcome %}
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->



      {% block content %}
      {% endblock content %}



      <!-- Bootstrap 4 -->
      <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <!-- AdminLTE App -->
      <script type="text/javascript" src="{% static 'plugins/jquery/jquery-3.5.1.min.js' %}"></script>
      <script src="{% static 'dist/js/adminlte.js' %}"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


      {% block scripts %}

      <!-- ChartJS -->
      <script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
      <!-- Sparkline -->
      <script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
      <!-- JQVMap -->
      <script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
      <script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
      <!-- jQuery Knob Chart -->
      <script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
      <!-- daterangepicker -->
      <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
      <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>

      <!-- AdminLTE for demo purposes -->
      <script src="{% static 'dist/js/demo.js' %}"></script>
      <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
      <script src="{% static 'dist/js/pages/dashboard.js' %}"></script>


      <!-- Tempusdominus Bootstrap 4 -->
      <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
      <!-- Summernote -->
      <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
      <!-- overlayScrollbars -->
      <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>



      {% endblock scripts%}


    </div>
  </div>

</body>

</html>

Try2AcademicPortal/AcademicPortal/templates/dashboardPage/profile.html
{% extends 'dashboardPage/dashboard.html' %}
{% load static %}
{% block welcome %}
{% endblock welcome %}
{% block content %}
<div class="col-md-9 personal-info">
        <h2><nbsp>Profile</h2>
</div>
<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="{% static avatar %}" alt=""/>
                    <div class="file btn btn-lg btn-primary">
                        <!--input type="file" name="file"/-->
                        .
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                            <h5>
                               {{name}}
                            </h5>
                            <h6>
                                Student
                            </h6>
                            <br><br><br><br><br>
                            <!--p class="proile-rating">RANKINGS : <span>8/10</span></p-->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Subjects</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <!--input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/-->
                <a class="btn btn-outline-info  btn-sm btn-block"  href="{%url 'dashboard:update_profile' %}">Edit Profile</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>WORK LINK</p>
                    <a href="{{website}}">Website Link</a><br/>
                    <a href="{{linked}}">LinkedIn Profile</a><br/>
                    <a href="{{github}}">Github Profile</a>
                    <p>SKILLS</p>
                    <a href="">Web Designer</a><br/>
                    <a href="">Web Developer</a><br/>
                    <a href="">Python</a><br/>
                    <a href="">C Programming</a><br/>
                    <a href="">Java Programming</a><br/>
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>USN</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{usn}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Name</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{name}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Sex</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{sex}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{email}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Branch</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{branch}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Semester</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{semester}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Bio</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{bio}}</p>
                                    </div>
                                </div>
                                
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Course 1</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{course1}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Course 2</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{course2}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Course 3</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{course3}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Course 4</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{course4}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Course 5</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{course5}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Course 6</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{course6}}</p>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>           
</div>
{% block scripts %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'plugins/jquery/jquery-3.5.1.min.js' %}"></script>
{% endblock scripts%}

{% endblock content%}