Try2AcademicPortal/AcademicPortal/AcademicPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('login/',login_view,name="login"),
    path('signup/',signup_view,name="signup"),
	path('logout/', logoutUser, name="logout"),

    path('',include('dashboard.urls')),
    
    path('cal/', include('calendarapp.urls')),

    path('todo/', include('todoapp.urls')),
    
    path('admin/', admin.site.urls),

    path('fileupload/',include('fileuploadapp.urls')),

    path('social/',include('social.urls'))
    
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Try2AcademicPortal/AcademicPortal/dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('', home_view, name='home'),
    path('profile/', profile_view, name='profile'),
    path('update_profile/',update_profile_view,name='update_profile'),
    path('aboutus/',aboutus,name='aboutus'),
]

Try2AcademicPortal/AcademicPortal/social/urls.py
from django.urls import path,include

from .views import *
app_name='social'
urlpatterns=[
	path('',index,name="home"),
	path('upload/',show_file,name="upload"),
	path('upload/<int:pk>/',delete_book,name="delete_book"),

]

Try2AcademicPortal/AcademicPortal/social/models.py
from django.db import models

# Create your models here.
class document_upload(models.Model):
    BRANCH = [
        ('CST','CST'),
        ('CSE','CSE'),
        ('ECE','ECE'),
        ('BCA','BCA'),
        ('Aerospace','Aerospace'),
        ('Mechanical','Mechanical')
    ]

    SEMESTER=[
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
        ('6','6'),
        ('7','7'),
        ('8','8'),
    ]

    branch = models.CharField(max_length=255,null=True,choices=BRANCH)
    semester = models.CharField(max_length=255,null=True,choices=SEMESTER)
    course = models.CharField(max_length=255,null=True)
    file_name = models.CharField(max_length=255,null=True)
    my_file = models.FileField(upload_to='')

    def __str__(self):
        return self.file_name

	

Try2AcademicPortal/AcademicPortal/social/forms.py
from django import forms

class DocumentUploadForm(forms.Form):
	BRANCH = (
        ('CST','CST'),
        ('CSE','CSE'),
        ('ECE','ECE'),
        ('BCA','BCA'),
        ('Aerospace','Aerospace'),
        ('Mechanical','Mechanical'))
	SEMESTER = (
		('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
        ('6','6'),
        ('7','7'),
        ('8','8'))
	branch = forms.ChoiceField(label='Branch',widget=forms.Select(attrs={'class':'form-control'}),choices=BRANCH)
	semester = forms.ChoiceField(label='Semester',widget=forms.Select(attrs={'class':'form-control'}),choices=SEMESTER)
	course = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	file_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	my_file=forms.FileField(widget=forms.FileInput(attrs={'class':'form-control'}))

Try2AcademicPortal/AcademicPortal/social/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import DocumentUploadForm
from .models import document_upload
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='login')
def index(request):
    if request.method=='POST':
        form = DocumentUploadForm(request.POST, request.FILES)
        if form.is_valid():
            branch = form.cleaned_data['branch']
            semester = form.cleaned_data['semester']
            course = form.cleaned_data['course']
            file_name = form.cleaned_data['file_name']
            my_file = form.cleaned_data['my_file']
            document_upload(branch=branch,semester=semester,course=course,file_name=file_name,my_file=my_file).save()
            return redirect('social:upload')
        else:
            return HttpResponse('ERROR')

    context={'form': DocumentUploadForm()}
    return render(request,'social/index.html',context)


def show_file(request):
	all_data=document_upload.objects.all()

	context={
		'data':all_data
	}

	return render(request,'social/views.html',context)

@login_required(login_url='login')
def delete_book(request,pk):
	if request.method=='POST':
		book=document_upload.objects.get(pk=pk)
		book.delete()
	return redirect('social:upload')

Try2AcademicPortal/AcademicPortal/templates/social/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    Student Portal | Social
  </title>
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="/static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/adminlte.min.css">

</head>
<body>
  <div class="text-center">
    <br>
  <h4 style="align-self: center;">Social DocHub</h4>
  <hr>
</div>  
  <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      
{% block content %}
  <div class="container mt-5">
    <br>
    <form enctype="multipart/form-data" action="{% url 'social:home' %}" method="POST">

      <div class="form-group">
        <label for="{{form.branch.id_for_label}}">Branch</label>
        {{form.branch}}
  
      </div>

      <div class="form-group">
        <label for="{{form.semester.id_for_label}}">Semester</label>
        {{form.semester}}
      </div>

      <div class="form-group">
        <label for="{{form.semester.id_for_label}}">Course</label>
        {{form.course}}
      </div>
        
      
      <div class="form-group">
          <label for="{{form.file_name.id_for_label}}">File Name</label>
          {{form.file_name}}
    
        </div>


        <div class="form-group">
          <label for="{{form.my_file.id_for_label}}">FILE</label>
          {{form.my_file}}
        </div>
        {% csrf_token %}

        <button type="submit" class="btn btn-primary">Submit</button>
   </form>
    <br>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{%endblock%}

</div>
</body>
</html>

Try2AcademicPortal/AcademicPortal/templates/social/views.html
{% extends 'social/index.html' %}
{%block content%}
<div class="container mt-5">
	<br>
	<div class="row">
		<div class="col-12">

			<p>
				<a href="{% url 'dashboard:home' %}" class="btn btn-primary">Home</a>
			</p>

			<p>
				<a href="{% url 'social:home' %}" class="btn btn-primary">Upload</a>
			</p>
			<table class="table">
				<thead class="thead-dark">
					<tr>
						<th>Sl.No</th>
						<th>Name</th>
						<th>Branch</th>
						<th>Semester</th>
						<th>Course</th>
						<th>File Link</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tbody>
					{% for d in data %}

					<tr>

						<th>{{forloop.counter}}</th>
						<th>{{d.file_name}}</th>
						<th>{{d.branch}}</th>
						<th>{{d.semester}}</th>
						<th>{{d.course}}</th>
						<th><a href="{{d.my_file.url}}">{{d.my_file}}</a></th>

						<th>
							<form method="post" action="{% url 'social:delete_book' d.pk %}">
								{% csrf_token %}
								<button type="submit" class="btn btn-danger btn-sm">Delete</button>
							</form>
						</th>
					</tr>
					{% endfor %}
			</table>
			<br>
		</div>
	</div>
</div>
{%endblock%}