Try2AcademicPortal/AcademicPortal/AcademicPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('login/',login_view,name="login"),
    path('signup/',signup_view,name="signup"),
	path('logout/', logoutUser, name="logout"),

    path('',include('dashboard.urls')),
    
    path('cal/', include('calendarapp.urls')),

    path('todo/', include('todoapp.urls')),
    
    path('admin/', admin.site.urls),

    path('fileupload/',include('fileuploadapp.urls')),

    path('social/',include('social.urls'))
    
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Try2AcademicPortal/AcademicPortal/calendarapp/urls.py
from django.urls import path

from .views import *

app_name = 'calendarapp'
urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/', create_event, name='event_new'),
    path('event/edit/<int:pk>/', EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', EventMemberDeleteView.as_view(), name="remove_event"),
]

Try2AcademicPortal/AcademicPortal/social/urls.py
from django.urls import path,include

from .views import *
app_name='social'
urlpatterns=[
	path('',index,name="home"),
	path('upload/',show_file,name="upload"),
	path('upload/<int:pk>/',delete_book,name="delete_book"),

]

Try2AcademicPortal/AcademicPortal/templates/calendarPage/add_member.html
{% extends 'dashboardPage/dashboard.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block welcome %}
{% endblock welcome %}
{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

Try2AcademicPortal/AcademicPortal/templates/calendarPage/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

Try2AcademicPortal/AcademicPortal/templates/calendarPage/calendar.html
{% extends 'dashboardPage/dashboard.html' %}

{%block title%}
  Student Portal | Calendar
  {%endblock%}

{% block welcome %}
{% endblock welcome %}
{% block content %}

<div class="clearfix" bac>
    <span class="left m-2" style="font-size: 20px;">Welcome, {{ request.user.username }}</span>
	<a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> + New Event </a>
</div>
<div style="color: rgb(7, 7, 7);">
    {{ calendar }}
</div>
{% endblock %}

Try2AcademicPortal/AcademicPortal/templates/calendarPage/event-details.html
{% extends 'dashboardPage/dashboard.html' %}


{% block title %}
Event Details
{% endblock %}

{% block welcome %}
{% endblock welcome %}
{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
        </div>
        
        <div class="clearfix">
            <h3>Event Name: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>                  
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

Try2AcademicPortal/AcademicPortal/templates/calendarPage/event.html
{% extends 'dashboardPage/dashboard.html' %}


{% block title %}
Event
{% endblock %}

{% block welcome %}
{% endblock welcome %}
{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Back </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

Try2AcademicPortal/AcademicPortal/templates/calendarPage/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'dashboardPage/dashboard.html' %}
{% block title %}
Delete Event
{% endblock %}

{% block welcome %}
{% endblock welcome %}
{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}